In [1]:
import numpy as np


In [8]:
a=np.zeros(4); print(a,a.shape)
a=np.zeros(4,); print(a,a.shape)
a=np.random.random_sample(4); print(a,a.shape)

[0. 0. 0. 0.] (4,)
[0. 0. 0. 0.] (4,)
[0.48499496 0.99763326 0.15089455 0.14949711] (4,)


In [11]:
a=np.arange(4.);print(a,a.shape)
a=np.random.rand(4); print(a,a.shape)

[0. 1. 2. 3.] (4,)
[0.80480673 0.53002856 0.7085743  0.36843295] (4,)


In [12]:
a=np.array([1,1,1,1,1,1,1,1,1,1,1,1]); print(a,a.shape)


[1 1 1 1 1 1 1 1 1 1 1 1] (12,)


## Indexing

In [16]:
a=np.arange(10)
print(a,a.shape)
print(a[2],a[2].shape) # scaler dont have any dimensions

try:
    a[10]
except Exception as e:
    print("Error in indexing")
    print(e)

[0 1 2 3 4 5 6 7 8 9] (10,)
2 ()
Error in indexing
index 10 is out of bounds for axis 0 with size 10


## Slicing

In [25]:
a=np.arange(10)
print(a,a.shape)
print(a[:]) # print all the elements of a
print(a[2:7:2]) #start:end:step
print(a[2:]) # 2 or 2 se aagay
print(a[:4]) # 4 is not included

[0 1 2 3 4 5 6 7 8 9] (10,)
[0 1 2 3 4 5 6 7 8 9]
[2 4 6]
[2 3 4 5 6 7 8 9]
[0 1 2 3]


## vector oprations

In [30]:
a=np.arange(20) ;print(a)

print(np.mean(a))
print(np.sum(a)) 
print(a**2)


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
9.5
190
[  0   1   4   9  16  25  36  49  64  81 100 121 144 169 196 225 256 289
 324 361]


In [35]:
b=np.arange(20,40)
print(b)
print(b*5)
print(a+b)
print(np.dot(a,b))


[20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39]
[100 105 110 115 120 125 130 135 140 145 150 155 160 165 170 175 180 185
 190 195]
[20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50 52 54 56 58]
6270


In [36]:
import time

In [45]:
# dot product using  for loop
def my_dot_product(a,b):
    total=0
    
    for i in range(len(a)):
        total=total+a[i]*b[i]
    
    return(total)
    

In [47]:
a=np.random.rand(1000000)
b=np.random.rand(1000000)

tic=time.time()
c=np.dot(a,b)
tok=time.time()

print((tok-tic)*1000,"ms")

tic=time.time()
c=my_dot_product(a,b)
tok=time.time()

print((tok-tic)*1000,"ms")
del(a,b)

0.9677410125732422 ms
251.62863731384277 ms
